apiVersion: v1
kind: Service
metadata:
  name: everipixel-server
  namespace: everipixel
  labels:
    app: evtd
spec:
  type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: everipixel-server
